---
#-------------------------------
# General Site Settings

title: Seik Oh
logo:
author: Seik Oh
description: this is meta description
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
  - { name: About, link: "/about" }
  # - { name: Blog, link: "/blog" }
  - { name: Works, link: "/portfolio" }
  - { name: CV/Resume, link: "/cv" }
  # - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: "Hi! I'm <br> Seik <br> HCI × UX Researcher & Engineer"

social:
  - { icon: "ti-linkedin", link: "https://linkedin.com/in/seikoh" }
  - { icon: "ti-github", link: "https://github.com/glitterer" }
  - { icon: "ti-email", link: "mailto:seikoh@gatech.edu" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: >
  CS PhD student at Georgia Institute of Technology, advised by Dr. Jessica Roberts. specializing in Human–Computer Interaction and Learning Science & Technology.
  I turn complex problems into interfaces people learn fast and keep using. I bridge research and engineering—mixing interviews, experiments, and prototypes—to ship inclusive, measurable improvements.

blurb-btn-link: "/about"
blurb-btn-name: Learn more

# About Page

# Work Process Section
work-process:
  - title: "Research & Plan"
    icon: "assets/images/icons/plan.png"
    content: "Define goals, users, and constraints. Mixed-methods research, task analysis, success metrics."

  - title: "Design & Prototype"
    icon: "assets/images/icons/design.png"
    content: "Wireframes to hi-fi in Figma; interactive prototypes (React/Unity); accessibility-first patterns."

  - title: "Test & Deliver"
    icon: "assets/images/icons/print.png"
    content: "Usability studies, analytics instrumentation, iteration, and handoff with clear specs & insights."

# My Team Section (optional — keep empty or remove)
team: []

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: UX Research (qual + quant), color: "#fdb157", value: "90%" }
  - { name: Prototyping (Figma/React/Unity), color: "#9473e6", value: "88%" }
  - { name: Accessibility & Inclusive Design, color: "#bdecf6", value: "85%" }
  - { name: Data Visualization, color: "#ffbcaa", value: "82%" }
  - { name: Python / PyTorch / TensorFlow, color: "#c6e48b", value: "80%" }
  - { name: iOS (Swift/SwiftUI), color: "#ffd166", value: "75%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: "Graduate Research Assistant — TILES Lab (HCI & Data Viz)",
      icon: "icon-1.png",
      date: "Aug 2025 – Present",
      organization: "Georgia Institute of Technology, Atlanta, GA",
    }
  - {
      name: "Software Developer — NASA SUITS 2025 (Top 10 Finalist)",
      icon: "icon-2.png",
      date: "Sep 2024 – May 2025",
      organization: "RISD Rover & Brown University / Johnson Space Center",
    }
  - {
      name: "Research Assistant Intern — LNCC Lab (UI/UX, Accessibility)",
      icon: "icon-3.png",
      date: "Jun 2024 – Dec 2024",
      organization: "Brown University, Providence, RI",
    }
  - {
      name: "AR/VR Developer — NASA SUITS 2024 (Top 10 Finalist)",
      icon: "icon-1.png",
      date: "Dec 2023 – May 2024",
      organization: "RISD Rover & Brown University / Johnson Space Center",
    }
  - {
      name: "iOS Developer Learner — Apple Developer Academy",
      icon: "icon-2.png",
      date: "Sep 2022 – Dec 2022",
      organization: "POSTECH, Pohang, South Korea",
    }
  - {
      name: "Technical Assistant — KATE Conference",
      icon: "icon-3.png",
      date: "Jul 2021 – Aug 2021",
      organization: "Seoul, South Korea",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: "Ph.D. in Computer Science",
      date: "Aug 2025 – Present",
      organization: "Georgia Institute of Technology, Atlanta, GA, USA",
    }
  - {
      name: "Sc.M. in Computer Science",
      date: "May 2025",
      organization: "Brown University, Providence, RI, USA",
    }
  - {
      name: "B.S. in Computer Science & Engineering",
      date: "Feb 2022",
      organization: "Soongsil University, Seoul, South Korea",
    }
  - {
      name: "B.A. in English Language & Literature",
      date: "Feb 2022",
      organization: "Soongsil University, Seoul, South Korea",
    }

# #-------------------------------
# # Publications Section

# publications-title: Publications
# publications:
  - {
      To be Updated
    }
#   - {
#       title: "ContAQT: Interactive Data Visualization for Multi-Pollutant Air Quality Analysis",
#       authors: "ANONYMOUS AUTHOR(S)",
#       venue: "CHI 2026 (Submitted)",
#       year: "2025",
#       type: "Conference Paper",
#       status: "Submitted",
#       description: "An interactive visualization tool for exploring complex multi-pollutant air quality data with focus on accessibility and user comprehension.",
#       link: "#"
#     }

#-------------------------------
# # Services Section

# services-title: Services
# services:
#   - {
#       name: "UX Research",
#       icon: ti-user,
#       description: "Mixed methods—interviews, usability testing, surveys, field/remote studies; study plans, scripts, and actionable reports.",
#       active: true,
#     }
#   - {
#       name: "UX Engineering",
#       icon: ti-panel,
#       description: "Rapid prototyping in Figma/React/Unity, instrumentation & analytics, design systems, accessibility-first implementation.",
#       active: true,
#     }
#   - {
#       name: "Data Visualization",
#       icon: ti-bar-chart,
#       description: "Interactive visualization for complex datasets; clarity, narrative, and decision support.",
#       active: true,
#     }

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section (replace images with your own)
portfolio-home-items:
  - image: "assets/images/portfolio/suits-2025.png"
    url: "#"
  - image: "assets/images/portfolio/adhd-redesign.png"
    url: "#"
  - image: "assets/images/portfolio/contaqt.png"
    url: "#"
  - image: "assets/images/portfolio/spaceover.png"
    url: "#"
  - image: "assets/images/portfolio/dataviz.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UX Research", type: "uxr" }
  - { title: "UX Engineering", type: "uxeng" }
  - { title: "Data Visualization", type: "dataviz" }
  - { title: "AR/VR", type: "arvr" }
  - { title: "iOS", type: "ios" }
  - { title: "Accessibility", type: "a11y" }

portfolio-items:
  - image: "assets/images/portfolio/suits-2025.png"
    url: "#"
    portfolio-type:
      - type: "arvr"
      - type: "uxeng"
      - type: "uxr"

  - image: "assets/images/portfolio/suits-2024.png"
    url: "#"
    portfolio-type:
      - type: "arvr"
      - type: "uxeng"

  - image: "assets/images/portfolio/adhd-redesign.png"
    url: "#"
    portfolio-type:
      - type: "uxr"
      - type: "a11y"

  - image: "assets/images/portfolio/contaqt.png"
    url: "#"
    portfolio-type:
      - type: "dataviz"
      - type: "uxr"

  - image: "assets/images/portfolio/spaceover.png"
    url: "#"
    portfolio-type:
      - type: "ios"
      - type: "a11y"
      - type: "uxeng"

  - image: "assets/images/portfolio/emotion-recognition.png"
    url: "#"
    portfolio-type:
      - type: "dataviz"
      - type: "uxeng"

# #-------------------------------
# # Testimonials Section

# testimonial-items: []

# #-------------------------------
# # Client Slider Section

# client-slider-items: []

# #-------------------------------
# # Contact Section

# contact-title: Contact
# contact-email: seikoh@gatech.edu
